package com.bizmiz.gulbozor.core.utils

object Constant {
    const val BASE_URL = "http://185.217.131.168:8080/"
    const val MERGE_ID = "62aab750c5c5a513f84a87ff"
    const val SHOP_ID = 1
    const val BUCKET_CATEGORY_ID = 4
    const val HOUSE_PLANTS_CATEGORY_ID = 5
    const val ARCHA_CATEGORY_ID = 6
    const val LANDSCAPE_CATEGORY_ID = 7
    const val FRUIT_TREE_CATEGORY_ID = 8
    const val TREE_CATEGORY_ID = 2
    const val POT_CATEGORY_ID = 9
    const val DUNG_CATEGORY_ID = 10
    const val SMS_TOKEN =
        "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjk0NCwicm9sZSI6InVzZXIiLCJkYXRhIjp7ImlkIjo5NDQsIm5hbWUiOiJPT08gV0VCIEdVTCBCQVpBUiIsImVtYWlsIjoiZ29sZGNvZGVyOTk4QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiYXBpX3Rva2VuIjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2prME5Dd2ljbTlzWlNJNkluVnpaWElpTENKa1lYUmhJanA3SW1sa0lqbzVORFFzSW01aGJXVWlPaUpQVDA4Z1YwVkNJRWRWVENCQ1FWcEJVaUlzSW1WdFlXbHNJam9pWjI5c1pHTnZaR1Z5T1RrNFFHZHRZV2xzTG1OdmJTSXNJbkp2YkdVaU9pSjFjMlZ5SWl3aVlYQnBYM1J2YTJWdUlqb2laWGxLTUdWWVFXbFBhVXBMVmpGUmFVeERTbWhpUjJOcFQybEtTVlY2U1RGT2FVIiwic3RhdHVzIjoiYWN0aXZlIiwic21zX2FwaV9sb2dpbiI6ImVza2l6MiIsInNtc19hcGlfcGFzc3dvcmQiOiJlJCRrIXoiLCJ1el9wcmljZSI6NTAsInVjZWxsX3ByaWNlIjo1MCwiYmFsYW5jZSI6MzA0NzUwLCJpc192aXAiOjAsImhvc3QiOiJzZXJ2ZXIxIiwiY3JlYXRlZF9hdCI6IjIwMjItMDctMjZUMTI6MDA6MjcuMDAwMDAwWiIsInVwZGF0ZWRfYXQiOiIyMDIyLTA3LTI5VDA5OjA1OjAzLjAwMDAwMFoifSwiaWF0IjoxNjU5MTk4NjIzLCJleHAiOjE2NjE3OTA2MjN9.QOqzjTYBD7-KvBeUZ6iy1ghxK_tJgIf04aAhiR3yCWI"
}