package com.bizmiz.gulbozor.ui.bottom_nav.categories.shops_category.oneShop.model

data class Content(
    val active: Boolean,
    val allowed: Boolean,
    val callingCount: Any,
    val categoryId: Int,
    val cityId: Int,
    val createAt: String,
    val department: Int,
    val description: String,
    val diameter: Int,
    val height: Int,
    val id: Int,
    val image1: String,
    val image2: String,
    val image3: String,
    val image4: String,
    val image5: String,
    val image6: String,
    val image7: String,
    val image8: String,
    val phoneNumber: String,
    val price: Int,
    val regionId: Int,
    val seller: Boolean,
    val sellerId: Int,
    val shopId: Int,
    val title: String,
    val topNumber: Int,
    val weight: Int,
    val withFertilizer: Boolean,
    val withPot: Boolean
)